image: Visual Studio 2019

build:
  verbosity: detailed

artifacts:
  - path: '**\Release\*.nupkg'

build_script:
  - cmd: dotnet build -c Release

deploy:
  - provider: NuGet
    api_key:
      secure: deMIovwualxuedHRqQ5KApSJj+jaIMRK3eI+T09L7oyycWe/5VGeMi0I2JnlVgeL
    on:
      appveyor_repo_tag: true
