image: Visual Studio 2019

build:
  verbosity: detailed

cache:
  - '%USERPROFILE%\.nuget\packages -> paket.lock'

install:
  - dotnet tool restore

build_script:
  - cmd: dotnet fake build -t CiBuild

artifacts:
  - path: 'dist\*.nupkg'

deploy:
  - provider: NuGet
    api_key:
      secure: deMIovwualxuedHRqQ5KApSJj+jaIMRK3eI+T09L7oyycWe/5VGeMi0I2JnlVgeL
    on:
      appveyor_repo_tag: true
